idmap: override btrfs_ioctl_vol_args_v2 if system header doesn't have subvolid
The struct btrfs_ioctl_vol_args_v2 in /usr/include/linux/btrfs.h on my
system predates the inclusion of the "subvolid" field.  This causes the
following build failure:

idmapped-mounts.c: In function 'btrfs_delete_subvolume_id':
idmapped-mounts.c:9730:6: error: 'struct btrfs_ioctl_vol_args_v2' has no member named 'subvolid'
 9730 |  args.subvolid = subvolid;
      |      ^

Since this source file contains its own more uptodate copy of that
structure, add some more autoconf/cpp magic so that we can override the
struct definition if the system header doesn't have the desired field.

Signed-off-by: Darrick J. Wong <djwong@kernel.org>